name: Build & Push API Image

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    # Optional: build/test your .NET app first
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: dotnet restore
    - run: dotnet build --no-restore -c Release
    - run: dotnet test --no-build -c Release

    # Enable emulation & Buildx (needed for cross-arch builds)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push multi-arch
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Api/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/izush/aimail:latest
          ghcr.io/izush/aimail:sha-${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max