name: Build & Push API Image

on:
  push:
    branches: [ "main" ]   # change if you push to a different branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: izush/aimail   # <<< LOWERCASE owner/repo

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    # required to push to GHCR
    steps:
    - uses: actions/checkout@v4

    # Build & test on .NET 8 (adjust if your project targets 9 later)
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: dotnet restore
    - run: dotnet build --no-restore -c Release
    - run: dotnet test --no-build -c Release

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./src/Api          # update if your Dockerfile is elsewhere
        file: ./src/Api/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max